packages:
  device.base: !include device/base.yaml
  modules.web-server: !include device/modules/web-server.yaml

esphome:
  project:
    version: dev # This will be replaced by the github workflows with the `release` version
